### PR TITLE
feat: update macos hl + dylibs

### PR DESCRIPTION
**Pull request by qkdreyer**

### CODE REVIEW

**Comment by qkdreyer** [comment]
I could have also update mbedtls dylibs but since names differ I didn't

```
644 -rw-r--r--  1 qkdreyer  staff   850K 21 mar 18:30 /usr/local/lib/haxe/lib/redistHelper/0,4,8/redistFiles/mac/libmbedcrypto.0.dylib
 644 -rw-r--r--  1 qkdreyer  staff   456K 21 mar 18:30 /usr/local/lib/haxe/lib/redistHelper/0,4,8/redistFiles/mac/libmbedtls.10.dylib
 644 -rw-r--r--  1 qkdreyer  staff   206K 21 mar 18:30 /usr/local/lib/haxe/lib/redistHelper/0,4,8/redistFiles/mac/libmbedx509.0.dylib

 100 /usr/local/Cellar/mbedtls/2.26.0/lib:
total 3184
 644 -rw-r--r--  1 qkdreyer  staff   349K 19 mar 10:02 libmbedcrypto.2.26.0.dylib
 755 lrwxr-xr-x  1 qkdreyer  staff    26B 12 mar 17:55 libmbedcrypto.6.dylib@ -> libmbedcrypto.2.26.0.dylib
 444 -r--r--r--  1 qkdreyer  staff   530K 12 mar 17:55 libmbedcrypto.a
 755 lrwxr-xr-x  1 qkdreyer  staff    21B 12 mar 17:55 libmbedcrypto.dylib@ -> libmbedcrypto.6.dylib
 755 lrwxr-xr-x  1 qkdreyer  staff    23B 12 mar 17:55 libmbedtls.13.dylib@ -> libmbedtls.2.26.0.dylib
 644 -rw-r--r--  1 qkdreyer  staff   201K 19 mar 10:02 libmbedtls.2.26.0.dylib
 444 -r--r--r--  1 qkdreyer  staff   218K 12 mar 17:55 libmbedtls.a
 755 lrwxr-xr-x  1 qkdreyer  staff    19B 12 mar 17:55 libmbedtls.dylib@ -> libmbedtls.13.dylib
 755 lrwxr-xr-x  1 qkdreyer  staff    24B 12 mar 17:55 libmbedx509.1.dylib@ -> libmbedx509.2.26.0.dylib
 644 -rw-r--r--  1 qkdreyer  staff   148K 19 mar 10:02 libmbedx509.2.26.0.dylib
 444 -r--r--r--  1 qkdreyer  staff   129K 12 mar 17:55 libmbedx509.a
 755 lrwxr-xr-x  1 qkdreyer  staff    19B 12 mar 17:55 libmbedx509.dylib@ -> libmbedx509.1.dylib
 ```

**Comment by qkdreyer** [comment]
@deepnight 

```
src/module.c(311) : FATAL ERROR : Failed to load function std@bytes_compare16
```

**Comment by deepnight** [comment]
> 
> 
> @deepnight
> 
> ```
> src/module.c(311) : FATAL ERROR : Failed to load function std@bytes_compare16
> ```

Hi, I'm not sure to understand. Is this error related to your PR or any new change in latest Hashlink redists?

**Comment by qkdreyer** [comment]
It's related to the latest hl not being compatible with previous redistHelper dylibs

**Comment by qkdreyer** [comment]
Could you release a new version of redistHelper ?

**Comment by deepnight** [comment]
My bad, done :)

**Pull request merged**
